apiVersion: v1
kind: Pod
metadata:
  name: IAMTEST
  labels:
    aadpodidbinding: #demo  #TODO: need to inject this
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  securityContext:
   runAsUser: 1000
   runAsGroup: 3000
   fsGroup: 2000
   supplementalGroups: [ 1 ]
  containers:
  - name: demo
    image: {{ probr-compatible-image }}
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: false
  nodeSelector:
    kubernetes.io/os: linux