apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "localhost/unapproved-profile.json"
spec:  
  securityContext:
    runAsUser: 1000    
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [ 1 ]      
  containers:
  - name: sec-ctx-demo
    image: {{ probr-compatible-image }}
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: false            