apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:  
  securityContext:
    runAsUser: 1000    
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [ 1 ]    
  volumes:
   - name: approved-volume
     configMap:
        name: test-config-map        
  containers:
  - name: sec-ctx-demo
    image: {{ probr-compatible-image }}
    command: [ "sh", "-c", "sleep 1h" ]        
    volumeMounts:
    - name: approved-volume
      mountPath: /tmp/test
      
    securityContext:
      allowPrivilegeEscalation: false